package entity;
// Generated Dec 4, 2024 9:00:58 PM by Hibernate Tools 4.3.1

import java.awt.List;
import java.util.ArrayList;
import org.hibernate.Session;
import org.hibernate.Transaction;
import util.sepeda;


/**
 * StokSepeda generated by hbm2java
 */
public class StokSepeda  implements java.io.Serializable {


     private String idSpd;
     private String namaSepeda;
     private String modelSepeda;
     private String statusSepeda;
     private int jumlahSepeda;

    public StokSepeda() {
    }

    public StokSepeda(String idSpd, String namaSepeda, String modelSepeda, String statusSepeda, int jumlahSepeda) {
       this.idSpd = idSpd;
       this.namaSepeda = namaSepeda;
       this.modelSepeda = modelSepeda;
       this.statusSepeda = statusSepeda;
       this.jumlahSepeda = jumlahSepeda;
    }

    public StokSepeda(String idSpd, String namaSpd, String modelSpd, String sts, String jmlh) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   
    public String getIdSpd() {
        return this.idSpd;
    }
    
    public void setIdSpd(String idSpd) {
        this.idSpd = idSpd;
    }
    public String getNamaSepeda() {
        return this.namaSepeda;
    }
    
    public void setNamaSepeda(String namaSepeda) {
        this.namaSepeda = namaSepeda;
    }
    public String getModelSepeda() {
        return this.modelSepeda;
    }
    
    public void setModelSepeda(String modelSepeda) {
        this.modelSepeda = modelSepeda;
    }
    public String getStatusSepeda() {
        return this.statusSepeda;
    }
    
    public void setStatusSepeda(String statusSepeda) {
        this.statusSepeda = statusSepeda;
    }
    public int getJumlahSepeda() {
        return this.jumlahSepeda;
    }
    
    public void setJumlahSepeda(int jumlahSepeda) {
        this.jumlahSepeda = jumlahSepeda;
    }

    public static java.util.List<StokSepeda> read() {
        java.util.List<StokSepeda> a = new ArrayList<StokSepeda>();
        Transaction tran = null;
        Session session = sepeda.getSessionFactory().openSession();
        try {
            tran = session.beginTransaction();
            a = session.createQuery("from StokSepeda").list();
        } catch (RuntimeException e) {
            e.printStackTrace();
        } finally {
            session.flush();
            session.close();
        }
        return a;
    }



}


